default: &default
  redis:
    host: <%= ENV["QQUIZ_REDIS_HOST"] %>
    namespace: <%= ENV["QQUIZ_REDIS_NAMESPACE"] %>
    port: <%= ENV["QQUIZ_REDIS_PORT"] %>
  host:
    root: "http://localhost:3000/"
test:
  <<: *default
  host:
    root: "http://localhost:4000"
development:
  <<: *default
production:
  <<: *default
  host:
    root: "http://3.109.62.223:3000"