default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["QQUIZ_DB_HOST"] %>
  port: <%= ENV["QQUIZ_DB_PORT"] %>
  database: <%= ENV["QQUIZ_DB"] %>
  username: <%= ENV["QQUIZ_DB_USER"] %>
  password: <%= ENV["QQUIZ_DB_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
